### ISSUE TITLE
missing files like {dataset}_info.json , "gt_sdf_dir"  and "traj_file" of scannet

### ISSUE THREAD

**Issue by lanlan96** [facebookresearch/iSDF#1]
Hi! Thanks for your excellent work. While running the project, i find that there seems to miss some necessary files for working. Can you provide these files? Thanks

**Comment by joeaortiz** [comment]
These files can be downloaded using the bash download scripts as described in the readme: https://github.com/facebookresearch/iSDF#downloading-the-data
