### ISSUE TITLE
How to use Habitat simulator to get the stage SDF voxel?

### ISSUE THREAD

**Issue by ge35tay** [facebookresearch/iSDF#10]
First thanks for your great job! I notice that you use Habitat to get the stage SDF, i am curious how to use Habitat to calculate the SDF? Is there maybe a reference?

**Comment by liheqian1993** [comment]
First thanks for your great job! I'm a rookie of habitat-sim. Is there any code that explain how to "added a key event to the habitat-sim viewer that runs the above fn" you referred above? or is there a tutorial somewhere demonstraing this operation?
