### ISSUE TITLE
Moving

### ISSUE THREAD

**Issue by yanlong95** [facebookresearch/iSDF#11]
Hi, thanks for your excellent work.

I'm trying to repeat your work (replicaCAD), but I cannot move the camera around, and the keys do not work. May I know the device and Linux version you used? Thanks.

**Comment by joeaortiz** [comment]
Hi, can you give some more details of what you are running and what issue you are getting?

**Comment by yanlong95** [comment]
Hi Joe, Thanks for your reply.
I try to run iSDF on sequences with pose provided. I follow the readme instructions until the command _python train_vis.py --config configs/replicaCAD.json_. The window opens successfully but when I press the direction keys, the camera does not move. I wonder if my conda environment setup failed due to the device or Ubuntu version.

**Comment by joeaortiz** [comment]
I'm not sure what behaviour you were expecting but nothing should happen when you press the directions keys in the open3d vis window. The camera that is capturing the input depth images moves according the a prerecorded sequence, you cannot move this camera with your keys. If you are talking about the viewpoint of the 3D reconstruction window, then you can change this perspective by dragging with your mouse.
