### ISSUE TITLE
Dataset Download Fail

### ISSUE THREAD

**Issue by Jing-lun** [facebookresearch/iSDF#2]
Hi @joeaortiz, thanks for the amazing work!
Could you please fix the download link issues since those google drive links have reached the max download tries.

**Comment by joeaortiz** [comment]
Hi Jing-lu, the dataset download works for me. I think if there are a large number of downloads in a short period, google may block the download link for 24 hours, but it is working again now. 

Please reopen if you are still having issues.

**Comment by Jing-lun** [comment]
> Hi Jing-lu, the dataset download works for me. I think if there are a large number of downloads in a short period, google may block the download link for 24 hours, but it is working again now.
> 
> Please reopen if you are still having issues.

Hi Joe,

It's still not working on my side

---
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /drive/folders/1GTDhL0aXKv--YO0p6XLfYgSnMgzg1dXX?usp=sharing (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')))

**Comment by Jing-lun** [comment]
> @Jing-lun, you may be able to manually download from your browser using the links in the `iSDF/data/*.sh` files [here](https://github.com/facebookresearch/iSDF/blob/main/data/download_apt_2_nav.sh#L8) and [here](https://github.com/facebookresearch/iSDF/blob/main/data/download_data.sh#L8).

Since our working network just blocked the google drive for the safety issues, I might need to download it after back home, anyways, thank you for your guidance!
