### ISSUE TITLE
The code of ground truth SDF generation

### ISSUE THREAD

**Issue by jjhooon** [facebookresearch/iSDF#7]
First of all, I would like to thank you for your great work

I want to experiment with other scene data, but I cannot obtain ground truth SDF.
When can you open the code of ground truth SDF generation?

Thank you

**Comment by joeaortiz** [comment]
I provided some explanation here: https://github.com/facebookresearch/iSDF/issues/10#issuecomment-1237239673
Let me know if you need some more pointers to generate ground truth SDFs.

**Comment by jjhooon** [comment]
Thank you for explanation:) Let me check that comment

Actually, I have another question about quantitative results.
When I running code `isdf/eva/figs/all_seq.py` using result of `batch_train/jobs_local.py`, my plot is as follows.
<img width="639" alt="스크린샷 2022-09-06 오후 3 43 08" src="https://user-images.githubusercontent.com/81551992/188564830-c6adc7af-a699-480a-ba8b-28850ff8aac5.png">
I don't know why the results of SDF error and gradient cosine distance are weird. Can you help me with this result?

In my case, I use the CUDA 11.3 version and RTX A6000.

**Comment by jjhooon** [comment]
Additionally, I'm wondering how to generate all 'npy' files of each time steps in eval_pts folder. (e.g. surf_valid_gt_sdf.npy, vis_valid_gt_grad.npy, etc.)

Also, each time steps in eval_pts folder is set manually?
